# Introduction to Tensors


## 1.Creating tensors


In [ ]:
import torch
print(torch.__version__)

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Get the dimenstion of vector
vector.ndim

1

In [ ]:
# Get the shape of the vector
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[3,6],[5,8]])
MATRIX

tensor([[3, 6],
        [5, 8]])

In [ ]:
# Matrix dimension
MATRIX.ndim

2

In [ ]:
# Accessing matrix items
MATRIX[1]

tensor([5, 8])

In [ ]:
# Matrix shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [2,5,6],
    [10,2,1]
]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 2,  5,  6],
         [10,  2,  1]]])

In [ ]:
# TENSOR dimension (N.B: Numbers of brackets play a role)
TENSOR.ndim

3

In [ ]:
# TENSOR shape
TENSOR.shape

torch.Size([1, 3, 3])

### 1.1 Random tensors
They are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

In [ ]:
# Create random tensors of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1332, 0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274, 0.2696]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels *(R,G,B)
random_img_size_tensor, random_img_size_tensor.ndim

(tensor([[[0.4414, 0.2969, 0.8317],
          [0.1053, 0.2695, 0.3588],
          [0.1994, 0.5472, 0.0062],
          ...,
          [0.3397, 0.9565, 0.0660],
          [0.3421, 0.0172, 0.3031],
          [0.6576, 0.9813, 0.5840]],
 
         [[0.9902, 0.5978, 0.7888],
          [0.9008, 0.9180, 0.2201],
          [0.9597, 0.8029, 0.2662],
          ...,
          [0.1844, 0.8533, 0.5698],
          [0.3568, 0.1704, 0.6172],
          [0.0231, 0.6317, 0.7472]],
 
         [[0.0614, 0.1727, 0.1405],
          [0.9203, 0.9251, 0.5313],
          [0.9694, 0.3328, 0.0146],
          ...,
          [0.6272, 0.5955, 0.8636],
          [0.8345, 0.2273, 0.2865],
          [0.3940, 0.1418, 0.3650]],
 
         ...,
 
         [[0.5387, 0.1378, 0.9763],
          [0.5521, 0.6004, 0.1658],
          [0.1479, 0.8327, 0.2563],
          ...,
          [0.9871, 0.5877, 0.7375],
          [0.1551, 0.7881, 0.3759],
          [0.7442, 0.8621, 0.7548]],
 
         [[0.6381, 0.0106, 0.0893],
          [0

In [ ]:
# Create random tensors of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9663, 0.7687, 0.4566, 0.5745],
        [0.9200, 0.3230, 0.8613, 0.0919],
        [0.3102, 0.9536, 0.6002, 0.0351]])

### 1.2 Tensors of zeros and ones

In [ ]:
import torch

In [ ]:
# Create zeros tensor
zero_tensor = torch.zeros(size=(3,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Create ones tensor
ones_tensor = torch.ones(size=(3,4))
ones_tensor


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 1.3 Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Use steps
one_to_ten = torch.arange(start=0,end=12,step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

## 2.Tensor datatypes

### 2.1 Getting tensor information


In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # What device is our tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

### 2.2 Tensor operations
> * Addition
> * Substraction
> * Multiplication
> * Devision
> * Matrix Multiplication

In [ ]:

import torch
tensor = torch.rand(3,4)
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Size of tensor: {tensor.size()}")


Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])


In [ ]:
# Add 10
tensor = torch.tensor([1,2,3])
tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Substract with 20
tensor = torch.tensor([10,30,100])
tensor -= 20
tensor

tensor([-10,  10,  80])

In [ ]:
# Multiply by 10
tensor = torch.tensor([1,54,3])
tensor *= 10
tensor

tensor([ 10, 540,  30])

In [ ]:
# Divide by 5
tensor = torch.tensor([5,50,500])
tensor.divide(5)
tensor


tensor([  5,  50, 500])

In [ ]:
# Element wise multiplication
print(f"Operation: {tensor, "*", tensor}")
print(f"Wise multiplication result: {tensor*tensor}")
# Matrix Multiplication
print(f"Matrix multiplication result: {torch.matmul(tensor,tensor)}")



Operation: (tensor([  5,  50, 500]), '*', tensor([  5,  50, 500]))
Wise multiplication result: tensor([    25,   2500, 250000])
Matrix multiplication result: 252525


In [ ]:
# Multiplication by hand
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(f"Value: {value}")


Value: 252525
CPU times: user 960 µs, sys: 0 ns, total: 960 µs
Wall time: 1.7 ms


In [ ]:
# Multiplication by math module
%%time
torch.matmul(tensor,tensor)
#'@' symbol is also used for matrix muliplication

CPU times: user 668 µs, sys: 0 ns, total: 668 µs
Wall time: 1.17 ms


tensor(252525)

One of the most common errors in deep learning is shaping (3x2) @ (2x3) - works, but (3x2) @ (3x2) wont!


In [ ]:
# Shapes for matrix multiplication (not working example) 3x2 @ 3x2
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[6,7],
                        [8,9],
                        [10,11]])
torch.matmul(tensor_A,tensor_B)



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Transpose (fixing shape errors)
tensor_A = tensor_A.T
torch.matmul(tensor_A,tensor_B)


tensor([[ 80,  89],
        [104, 116]])

In [ ]:
# Shapes for matrix multiplication (working example) 3x2 @ 2x3


tensor_C = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_D = torch.tensor([[6,7,9],
                        [8,9,8]])
# mm is alias for mathmul
torch.mm(tensor_C,tensor_D)

tensor([[22, 25, 25],
        [50, 57, 59],
        [78, 89, 93]])

### 2.3 Tensor aggregation


In [ ]:
x = torch.arange(0,100,10)

# Find the min
torch.min(x), x.min()

# Find the max
torch.max(x), x.max()

# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

# Find the sum
torch.sum(x)

#Finding the positional min/max
x.argmin()
x.argmax()

tensor(9)

#### 2.3.1 Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1.,10)
x, x.shape

#Add extra dimension (hint: square bracket)
x_reshaped = x.reshape(1,9)
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# Change the view - It SHARES the memory with original tensor! (z is different view of x)
z = x.view(1,9)
z,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other with dim1  (rearrange it in columns)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze -> remove all single dimensions
print(f"Previous tensor {x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")

x_squuezed = x_reshaped.squeeze()

print(f"Squeezed tensor {x_squuezed}")
print(f"Squeezed tensor shape {x_squuezed}")

Previous tensor tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape torch.Size([1, 9])
Squeezed tensor tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed tensor shape tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# torch.unsqueeze -> adds a sinmgle dimension at a specific dim
print(f"Previous tensor {x_squuezed}")
print(f"Previous shape {x_squuezed.shape}")

# It can also rearrange the dimmension dim -> dim=0 == row; dim==1 == column
x_unsqueezed = x_squuezed.unsqueeze(dim=0)

print(f"Unsqueezed tensor {x_unsqueezed}")
print(f"Unsqueezed tensor shape {x_unsqueezed.shape}")

Previous tensor tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape torch.Size([9])
Unsqueezed tensor tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Unsqueezed tensor shape torch.Size([1, 9])


In [ ]:
# torch.permute -> returns a view of the original tensor with its dimensions permuted

x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels(RGB)]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # color channels [height, width]



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#### 2.3.2 Indexing (select data from tensors)

In [ ]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on the middle bracket: [][] [,]
x[0][0]
x[0,0]

tensor([1, 2, 3])

In [ ]:
# Index of the most inner bracket
x[0][0][0]

tensor(1)

In [ ]:
# ':' to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 1st and 2nd dim, but 1st of 2rd dim:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
# Get all values of 1st but only 1 index values of 1st and 2nd dim
x[:,1,2]

tensor([6])

In [ ]:
# Index on x to return 9
x[:,2,2]
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## 3.PyTorch tensors & NumPy

In [ ]:
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tensor = torch.from_numpy(arr)
arr,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Default NumPy dtype
# Warning! PyTorch reflect NumPy default dtype unless specified otherwise (dtype issue possible!)
arr.dtype

dtype('float64')

In [ ]:
# Change the value of array
array = arr + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the value of tensor
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 4.Reproducibility (trying to take random out of random)

`start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ->again...`

To reduce the randomness in neural networks and PyTorch come the concept of **random seed**

In [ ]:
import torch

# Create 2 random tensors

random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)

print(f"Random tensor A: \n{random_tensor_A}\n")
print(f"Random tensor B: \n{random_tensor_B}\n")
print(f"Equality: \n{random_tensor_A == random_tensor_B}")



Random tensor A: 
tensor([[0.0947, 0.9914, 0.0968],
        [0.1696, 0.8875, 0.5784],
        [0.8878, 0.1064, 0.1506]])

Random tensor B: 
tensor([[0.2984, 0.8520, 0.3450],
        [0.8201, 0.2874, 0.6248],
        [0.6197, 0.5040, 0.7213]])

Equality: 
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
# Make some random, but reproducible tenors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,3)

print(f"Random tensor C: \n{random_tensor_C}\n")
print(f"Random tensor D: \n{random_tensor_D}\n")
print(f"Equality: \n{random_tensor_C == random_tensor_D}")

# Torch.manual_seed works only for 1 line of code!!!



Random tensor C: 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Random tensor D: 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Equality: 
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## 5.Running tensors and PyTorch object on the GPUs
> 1. Easiest - Use Google Colab for free GPU
> 2. Use your own -  but it takes some time of setup and ivestments
> 3. Use cloud computing - GCP, AWS, Azure and etx.

Start locally: https://pytorch.org/get-started/locally/

Device agnostics: https://docs.pytorch.org/docs/stable/notes/cuda.html

In [ ]:
# Commands for using Coolab GPUs
!nvidia-smi
torch.cuda.is_available()


Sun Apr  5 13:15:44 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count the number of devices
torch.cuda.device_count()

0

### 5.1 Putting tensors (and models) on the GPU (Faster computations)


In [ ]:
# Create a tensor(default on the CPU)
tensor = torch.tensor([1,2,3], device = "cpu")

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu= tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3])

### 5.2 Moving tensors back to the CPU


In [ ]:
tensor_on_gpu.numpy()

array([1, 2, 3])